apiVersion: v1
kind: Service
metadata:
  namespace: base
  name: simple-uuid-microservice-service
spec:
  selector:
    app: simple-uuid-microservice-deployment
  ports:
    - protocol: TCP
      port: 9376
      targetPort: 8080